# Generated by Django 3.1.7 on 2021-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер клиента')),
                ('address', models.CharField(max_length=40, verbose_name='Адрес клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('product', models.ManyToManyField(related_name='products', to='webapp.Product', verbose_name='Товары')),
            ],
        ),
    ]
