# Generated by Django 3.1.7 on 2021-05-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210428_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediatetable',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_order', to='webapp.order'),
        ),
        migrations.AlterField(
            model_name='intermediatetable',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='webapp.product'),
        ),
    ]
